/**
 * 半自動センサー校正器「コウセイくん☆」Web API
 * 情報工学実験1A 実世界センシングで作成した半自動センサー校正器「コウセイくん☆」のWeb APIです。このWeb APIを利用することにより、Webページ、LINE、Discordなど様々なフロントエンドからコウセイくん☆を利用することができます。
 *
 * OpenAPI spec version: 1.0.0
 * Contact: yuma140902@gmail.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("donePost", () => {
    return expect(instance.donePost({})).resolves.toBe(null)
  })
  test("healthGet", () => {
    return expect(instance.healthGet({})).resolves.toBe(null)
  })
  test("mPost", () => {
    const body: api.MBody = {
  "index" : 42,
  "value" : 12.345
}
    return expect(instance.mPost(body, {})).resolves.toBe(null)
  })
  test("modelPut", () => {
    return expect(instance.modelPut({})).resolves.toBe(null)
  })
  test("startPost", () => {
    return expect(instance.startPost({})).resolves.toBe(null)
  })
})

