/* tslint:disable */
/* eslint-disable */
/**
 * 半自動センサー校正器「コウセイくん☆」Web API
 * 情報工学実験1A 実世界センシングで作成した半自動センサー校正器「コウセイくん☆」のWeb APIです。このWeb APIを利用することにより、Webページ、LINE、Discordなど様々なフロントエンドからコウセイくん☆を利用することができます。
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yuma140902@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DoneResponseParametersInner } from './DoneResponseParametersInner';
import {
    DoneResponseParametersInnerFromJSON,
    DoneResponseParametersInnerFromJSONTyped,
    DoneResponseParametersInnerToJSON,
} from './DoneResponseParametersInner';

/**
 * 
 * @export
 * @interface DoneResponse
 */
export interface DoneResponse {
    /**
     * 
     * @type {string}
     * @memberof DoneResponse
     */
    expression: string;
    /**
     * 
     * @type {Array<DoneResponseParametersInner>}
     * @memberof DoneResponse
     */
    parameters: Array<DoneResponseParametersInner>;
}

/**
 * Check if a given object implements the DoneResponse interface.
 */
export function instanceOfDoneResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "expression" in value;
    isInstance = isInstance && "parameters" in value;

    return isInstance;
}

export function DoneResponseFromJSON(json: any): DoneResponse {
    return DoneResponseFromJSONTyped(json, false);
}

export function DoneResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoneResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'expression': json['expression'],
        'parameters': ((json['parameters'] as Array<any>).map(DoneResponseParametersInnerFromJSON)),
    };
}

export function DoneResponseToJSON(value?: DoneResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'expression': value.expression,
        'parameters': ((value.parameters as Array<any>).map(DoneResponseParametersInnerToJSON)),
    };
}

