/* tslint:disable */
/* eslint-disable */
/**
 * 半自動センサー校正器「コウセイくん☆」Web API
 * 情報工学実験1A 実世界センシングで作成した半自動センサー校正器「コウセイくん☆」のWeb APIです。このWeb APIを利用することにより、Webページ、LINE、Discordなど様々なフロントエンドからコウセイくん☆を利用することができます。
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yuma140902@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoneResponseParametersInner
 */
export interface DoneResponseParametersInner {
    /**
     * 
     * @type {string}
     * @memberof DoneResponseParametersInner
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof DoneResponseParametersInner
     */
    value: number;
}

/**
 * Check if a given object implements the DoneResponseParametersInner interface.
 */
export function instanceOfDoneResponseParametersInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function DoneResponseParametersInnerFromJSON(json: any): DoneResponseParametersInner {
    return DoneResponseParametersInnerFromJSONTyped(json, false);
}

export function DoneResponseParametersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoneResponseParametersInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function DoneResponseParametersInnerToJSON(value?: DoneResponseParametersInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
    };
}

