/* tslint:disable */
/* eslint-disable */
/**
 * 半自動センサー校正器「コウセイくん☆」Web API
 * 情報工学実験1A 実世界センシングで作成した半自動センサー校正器「コウセイくん☆」のWeb APIです。このWeb APIを利用することにより、Webページ、LINE、Discordなど様々なフロントエンドからコウセイくん☆を利用することができます。
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: yuma140902@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MResponse
 */
export interface MResponse {
    /**
     * 
     * @type {number}
     * @memberof MResponse
     */
    index: number;
    /**
     * 
     * @type {number}
     * @memberof MResponse
     */
    v: number;
}

/**
 * Check if a given object implements the MResponse interface.
 */
export function instanceOfMResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "index" in value;
    isInstance = isInstance && "v" in value;

    return isInstance;
}

export function MResponseFromJSON(json: any): MResponse {
    return MResponseFromJSONTyped(json, false);
}

export function MResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'index': json['index'],
        'v': json['v'],
    };
}

export function MResponseToJSON(value?: MResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'index': value.index,
        'v': value.v,
    };
}

